window.SUPABASE_URL = 'https://genhqupgvmjbyvascybk.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbmhxdXBndm1qYnl2YXNjeWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyMTMzNTEsImV4cCI6MjEwNTc4OTM1MX0.aRd_jFlLEaEHv07prtwU3xo-tUrHtupp3hAZ-KN-WTs';
